platform :ios, '11.0'

target 'Smart Air Visul' do
  use_frameworks!
  pod 'Moya', '~> 13.0'

  target 'Smart Air VisulTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Smart Air VisulUITests' do
    # Pods for testing
  end

end
